 routes:
   -
     name: Web traffic
     id: blueprint-web
     uri: /*
     hosts:
       - ${WEB_HOST}
     upstream:
       nodes:
         "blueprint-web.webserver:80": 1
       type: roundrobin
   -
     name: Search Proxy
     id: blueprint-search
     uri: /search/*
     hosts:
       - ${WEB_HOST}
     upstream:
       nodes:
         "blueprint-search:8080": 1
       type: roundrobin
   -
     name: ingestion-api
     id: rest-ingestion
     uri: /*
     hosts:
       - ${STREAMX_INGESTION_HOST}
     upstream:
       nodes:
         "rest-ingestion:8080": 1
       type: roundrobin
 #END
